### PR TITLE
Gh5430 - report server: autodetect and use workspace jasperreports folders

### PR DESCRIPTION
**Pull request by teosarca**
https://github.com/metasfresh/metasfresh/issues/5430

### CODE REVIEW

**Comment by teosarca** [comment]
image

**Comment by teosarca** [comment]
e.g.
image

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperJdbcConnection.java  9
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/OutputType.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoClassLoaderHook.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/util/DevelopmentWorkspaceJasperDirectoriesFinder.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperCompileClassLoader.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporterNature.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceRepository.java  3
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/ADJasperFillerTest.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperEngine.java  8
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporter.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperClassLoader.java  11
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperJdbcConnectionTest.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/rest/MgtRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/rest/ReportRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/server/AbstractReportEngine.java  2
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceService.java  7
- de.metas.report/report-service/src/main/java/de/metas/report/server/ReportContext.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/server/LocalReportServer.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/rest/BarcodeRestController.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoLocalFileLoader.java  11
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java  16
- de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java  6
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperClassLoaderTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/metasfresh/metasfresh/pullRequest?prid=4024797&bid=13916963)

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperClassLoader.java  11
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceRepository.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/rest/MgtRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporterNature.java  3
- de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java  6
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoLocalFileLoader.java  11
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/OutputType.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/rest/ReportRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/rest/BarcodeRestController.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperCompileClassLoader.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java  16
- de.metas.report/report-service/src/main/java/de/metas/report/util/DevelopmentWorkspaceJasperDirectoriesFinder.java  3
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperClassLoaderTests.java  1
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperJdbcConnectionTest.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperJdbcConnection.java  9
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/ADJasperFillerTest.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/server/ReportContext.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporter.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/server/LocalReportServer.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoClassLoaderHook.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperEngine.java  8
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceService.java  7
- de.metas.report/report-service/src/main/java/de/metas/report/server/AbstractReportEngine.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/metasfresh/metasfresh/pullRequest?prid=4024797&bid=13916963)

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperClassLoaderTests.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/rest/ReportRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceRepository.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/util/DevelopmentWorkspaceJasperDirectoriesFinder.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperEngine.java  8
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporterNature.java  3
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/OutputType.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java  16
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoLocalFileLoader.java  11
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperJdbcConnectionTest.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/server/AbstractReportEngine.java  2
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoClassLoaderHook.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceService.java  7
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperJdbcConnection.java  9
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporter.java  3
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/ADJasperFillerTest.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperClassLoader.java  11
- de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java  6
- de.metas.report/report-service/src/main/java/de/metas/report/rest/BarcodeRestController.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/rest/MgtRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/server/LocalReportServer.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/server/ReportContext.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperCompileClassLoader.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/metasfresh/metasfresh/pullRequest?prid=4024797&bid=13916963)

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperCompileClassLoader.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/util/DevelopmentWorkspaceJasperDirectoriesFinder.java  3
- de.metas.report/de.metas.report.jasper.client/src/main/java/de/metas/report/client/ReportsClient.java  6
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporterNature.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoLocalFileLoader.java  11
- de.metas.report/report-service/src/main/java/de/metas/report/server/ReportContext.java  3
- de.metas.report/de.metas.report.jasper.commons/src/main/java/de/metas/report/server/OutputType.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperReportFiller.java  16
- de.metas.report/report-service/src/main/java/de/metas/report/rest/BarcodeRestController.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/rest/ReportRestController.java  3
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperClassLoaderTests.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperEngine.java  8
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/MetasJRXlsExporter.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceService.java  7
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/JasperJdbcConnectionTest.java  1
- de.metas.report/report-service/src/main/java/de/metas/report/rest/MgtRestController.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JsonDataSourceRepository.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/OrgLogoClassLoaderHook.java  5
- de.metas.report/report-service/src/test/java/de/metas/report/jasper/ADJasperFillerTest.java  3
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperJdbcConnection.java  9
- de.metas.report/report-service/src/main/java/de/metas/report/server/LocalReportServer.java  5
- de.metas.report/report-service/src/main/java/de/metas/report/jasper/JasperClassLoader.java  11
- de.metas.report/report-service/src/main/java/de/metas/report/server/AbstractReportEngine.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/metasfresh/metasfresh/pullRequest?prid=4024797&bid=13916963)

**Pull request merged**
