### PR TITLE
Fix jenkins mobile ui build

### PR DESCRIPTION
**Pull request by mrie04**

### CODE REVIEW

**Review by metas-ts — APPROVED** [review]

**Comment by mrie04** [comment]
@Mergifyio copy middle_ages_uat

**Comment by cristinamghita** [comment]
@mergifyio copy science_vessel_uat

**Comment by mrie04** [comment]
@Mergifyio copy soft_panda_uat

**Comment by mrie04** [comment]
@Mergifyio copy release release_5.175

**Comment by mrie04** [comment]
@Mergifyio copy gray_knight_uat

**Comment by mrie04** [comment]
@Mergifyio copy gray_knight_uat

**Comment by cristinamghita** [comment]
@mergifyio copy neon_underwear_uat

**Comment by mrie04** [comment]
@Mergifyio copy tasty_ham_uat

**Comment by dm-ps** [comment]
https://github.com/Mergifyio copy big_coconut_uat

**Comment by mrie04** [comment]
@Mergifyio copy modus_operandi_uat

**Comment by mrie04** [comment]
@Mergifyio copy hard_encoded_uat

**Comment by mrie04** [comment]
@Mergifyio copy yoyo_hotfix

**Pull request merged**
