### PR TITLE
Drop single primary key column on some of the AD_*Access tables

### PR DESCRIPTION
**Pull request by teosarca**
- drop AD_Document_Action_Access_ID
- drop AD_Window_Access_ID
- drop AD_Form_Access_ID
- drop AD_Process_Access_ID
- drop AD_Task_Access_ID
- drop AD_Workflow_Access_ID

### CODE REVIEW

**Comment by metas-ts** [comment]
@mergifyio copy release release_5.175

**Comment by metas-ts** [comment]
Also CP it to the branches that have an 5.176 (RC) version
@Mergifyio copy release release_5.175 iron_plant_uat modified_carbon_uat inner_silence_uat koala_yawn_uat massive_entropy_uat mad_orange_uat

**Comment by metas-ts** [comment]
@Mergifyio copy release release_5.175 iron_plant_uat modified_carbon_uat inner_silence_uat koala_yawn_uat massive_entropy_uat mad_orange_uat 

...also CP it to the branches that have an 5.176 (RC) version

**Comment by teosarca** [comment]
removed the `patch_mgmt ` because this PR solves a problem but introduces other.

**Pull request merged**
