### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nebergd**
as implemented with lili please add to master

### CODE REVIEW

**Comment by metas-ts** [comment]
@nebergd i guess it's good that such a merge conflict happened early :-)

please let us know if you need help solving it. I think this particular is not too hard to solve...did you alread see the "Resolve conflict" button on this page?

**Comment by metas-ts** [comment]
Hi @nebergd 
I plan to close this pull request and a few others that did not see any changes over the last two weeks.

Please le me know if you are going to resolve the merge conflict and need some more time.
Otherwise, I set a reminder for the coming friday to close it.
Ofc you can also later open a new PR.

**Comment by nebergd** [comment]
Hi Tobias,

as I remember is this issue for hide the "rekapulation" and we solve 
this problem together with Lily...

Best Regards

Dieter


Am 01.02.2017 um 07:38 schrieb Tobias Schöneberg:

**Comment by metas-ts** [comment]
Closing this one now, but i added https://github.com/metasfresh/metasfresh/pull/905 to integrate all the things that yoiu and @metas-lc made

**Pull request closed without merging**
