### PR TITLE
Remove the action that leads to 404

### PR DESCRIPTION
**Pull request by petrican**
https://www.loom.com/share/cdc42b735f2b403d810b43650d875d21

## 1) Go to picking tray clearing
Screenshot 2021-06-16 at 16 32 06

## 2) Barcode on 2nd panel
Screenshot 2021-06-16 at 16 32 57

## 3) Input something
Screenshot 2021-06-16 at 16 33 28

## 4) Should see the error but the UI should remain unchanged. no 404 on the screen
Screenshot 2021-06-16 at 16 33 54

### CODE REVIEW

**Comment by siemiatj** [comment]
Until backend solves this, looks good to me

**Comment by petrican** [comment]
> @petrican @siemiatj any reason to not remove it from viewHandler.js and from all other files where FILTER_VIEW_ERROR is present?
> 
> image

Its indeed not used but I would leave it for now as it is. Reason: in the near future we'll most probably need to adapt it to deal with the refined errors we get from the BE and it is going to be a simpler to just see it on spot.

**Comment by teosarca** [comment]
@petrican understand.

that's not a good practice according to clean code principles (and not only, e.g. https://refactoring.guru/smells/dead-code, https://softwareengineering.stackexchange.com/questions/103031/should-i-remove-unreferenced-code),

but I can live with that now.

**Comment by metas-Kay** [comment]
related to https://github.com/metasfresh/metasfresh/issues/11305

**Pull request merged**
