### PR TITLE
Strip header and show only the error

### PR DESCRIPTION
**Pull request by petrican**
https://github.com/metasfresh/me03/issues/4324

https://www.loom.com/share/ffab0c7b224147f5ae6973441545e536

Screenshot 2020-11-10 at 09 19 20

### CODE REVIEW

**Comment by siemiatj** [comment]
I'm wondering if we shouldn't add `Error` text as well. @teosarca ?

**Comment by teosarca** [comment]
> I'm wondering if we shouldn't add Error text as well. @teosarca ?

@siemiatj  like to prefix it with `Error: `? 
... neahhhh... it's a popup with text in a red frame. isn't obvious that it's an error?

**Comment by petrican** [comment]
So can this be merged ? @teosarca @siemiatj

**Comment by teosarca** [comment]
@petrican  IMHO yes

**Pull request merged**
