### PR TITLE
fix external system startup and env-var usage with gh-actions image

### PR DESCRIPTION
**Pull request by mrie04**

### CODE REVIEW

**Comment by metas-ts** [comment]
@mergifyio copy big_coconut_uat_update_to_5.175 clone_wars_uat_update_to_5.175 epic_party_uat_update_to_5.175 majestic_kangaroo_uat_update_to_5.175 magic_oak_uat_update_to_5.175 secondary_opinion_uat_update_to_5.175 science_vessel_uat_update_to_5.175 tenacious_d_uat_update_to_5.175 tasty_ham_uat_update_to_5.175 yoyo_uat_update_to_5.175 zulu_alpha_uat_update_to_5.175

**Comment by metas-ts** [comment]
@mergifio copy hard_encoded_uat iron_plant_uat inner_silence_uat modified_carbon_uat koala_yawn_uat massive_entropy_uat release mad_orange_uat neon_underwear_uat pink_rooster_uat

**Comment by metas-ts** [comment]
@Mergifyio copy hard_encoded_uat iron_plant_uat inner_silence_uat modified_carbon_uat koala_yawn_uat massive_entropy_uat release mad_orange_uat neon_underwear_uat pink_rooster_uat

**Comment by metas-ts** [comment]
TODO: check branches with `...pr-17496`  - looks like mergify created them even if the code war already in the target-branch

**Comment by metas-ts** [comment]
@Mergifyio copy middle_ages_uat

**Comment by mrie04** [comment]
@Mergifyio copy release_5.175 vampire_textbook_uat

**Comment by metas-ts** [comment]
https://github.com/Mergifyio copy soft_panda_uat

**Comment by metas-ts** [comment]
@MergifyIO copy hard_encoded_hotfix intensive_care_hotfix mad_orange_hotfix pink_rooster_hotfix secondary_opinion_hotfix soft_panda_hotfix tasty_ham_hotfix yoyo_hotfix

**Pull request merged**
