### PR TITLE
FRESH-259: Completely remove zkwebui from metasfresh

### PR DESCRIPTION
**Pull request by teosarca**

### CODE REVIEW

**Comment by hriess** [comment]
What is your alternative Framework?

**Comment by metas-ts** [comment]
@hriess in our customer projects we didn't really use the webUI for quite some time, but instead our clients&customers used the swing client. For the nearer future, we are working on a vaadin based webUI.

**Comment by hriess** [comment]
Thank you for information.

We use zk8 community edition in our Idempiere 3.1 environment.

Is there a reason for stopping zk and migrating to Vaadin.

Regards

Hans
Am 28.04.2016 20:33 schrieb "Tobias Schöneberg" <notifications@github.com>:

**Comment by teosarca** [comment]
@hriess Some of the reasons we considered are how easy we can push more UI logic to client(browser), offline support, light components, mobile devices, responsive design, possibility to integrate with reactive frameworks and ofcourse, the community around the project.
Nevertheless, our aim is to have Vaadin only on View and/or Presenter layers.

**Comment by hriess** [comment]
For special purposes there is a need to create individual forms (e.g. payment allocation). Does Vaadin also support this?

**Comment by teosarca** [comment]
amazingly well ;)

**Comment by hriess** [comment]
I wish you success in creating the web ui based on this framework.

**Comment by teosarca** [comment]
thanks a lot... and stay tuned!

**Pull request merged**
