### PR TITLE
Fix flaky unit test TestTwoShipmentsOneInvoicePriceOverrideZero

### PR DESCRIPTION
**Pull request by metas-ts**

### CODE REVIEW

**Comment by metas-ts** [comment]
@MergifyIO copy iron_plant_uat inner_silence_uat koala_yawn_uat modified_carbon_uat

**Comment by metas-ts** [comment]
https://github.com/Mergifyio copy iron_plant_uat inner_silence_uat modified_carbon_uat

**Comment by adi-stefan** [comment]
https://github.com/Mergifyio copy inner_silence_uat

**Comment by metas-ts** [comment]
@Mergifyio copy iron_plant_uat

**Comment by metas-ts** [comment]
@mergifyio copy adorable_badger_uat

**Pull request merged**
