### PR TITLE
 #4123 Fix documentPaid function

### PR DESCRIPTION
**Pull request by cristinamghita**
#4123 Dunning Jasper does not work

### CODE REVIEW

**Comment by metas-ts** [comment]
on a search for documentpaid among *.java, *.sql files, it seems that only these four actually use it:
image

**Comment by cristinamghita** [comment]
@metas-ts Tobi, I am not sure about checking the order.
Because, now, as we refactor code and reimplemented prepay order, a prepay order is paid only when its invoice is paid.
And that is covered by these  2 lines:
```
LEFT OUTER JOIN C_Invoice i ON (al.C_Invoice_ID = i.C_Invoice_ID)
```
and
```
OR (i.C_Order_ID = p_Record_ID AND p_AD_Table_ID = (SELECT AD_Table_ID FROM AD_Table WHERE TableName = 'C_Order'))
```

**Comment by metas-ts** [comment]
so i suggest to just kick "C_Order" out as the quickest solution (2nd quickest: loos the whole funktion and make sure that `invoicepaid` works)

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Pull request merged**
