### PR TITLE
Fix resetting breadcrumbs

### PR DESCRIPTION
**Pull request by siemiatj**
Related to #10900

### CODE REVIEW

**Review by petrican — CHANGES_REQUESTED** [review]
The search does not function anymore - **NOK**
Screenshot 2021-07-30 at 07 23 30

If you directly put in the address bar the URI to SO 
http://localhost:3000/window/143 
and if you click on the first breadcrumb 
Screenshot 2021-07-30 at 07 26 02
you will end up in an empty page
Screenshot 2021-07-30 at 07 26 56

**Comment by petrican** [comment]
Screenshot 2021-07-30 at 07 28 36
Also while working on this pls try to replace that code such that the hotfix with window.location won't be used.. Thanks

**Comment by petrican** [comment]
Another issue found in this branch regarding the sitemap - going to the sitemap does not render the items and also they cannot be searched - **NOK**
Screenshot 2021-07-30 at 07 36 58
Screenshot 2021-07-30 at 07 38 41

**Comment by siemiatj** [comment]
@petrican Yeah, I haven't submitted this for a review yet.

**Comment by siemiatj** [comment]
> Screenshot 2021-07-30 at 07 28 36
> Also while working on this pls try to replace that code such that the hotfix with window.location won't be used.. Thanks

Looked into this while working on the routing, but it turned out to be too complicated to fix in a limited time.

**Comment by siemiatj** [comment]
Now it's ready for review.

**Comment by petrican** [comment]
This case doesn't seem to be fixed. 
1) Go to SO
Screenshot 2021-08-02 at 08 46 25
2) Click on the parent breadcrumb
Screenshot 2021-08-02 at 08 46 57
3) It leads to empty page. **NOK** 
Screenshot 2021-08-02 at 08 47 22

**Review by petrican — CHANGES_REQUESTED** [review]
Pls fix the case with parent breadcrumb. Thanks

**Comment by siemiatj** [comment]
> This case doesn't seem to be fixed.
> 
>     1. Go to SO
> 
> 
> Screenshot 2021-08-02 at 08 46 25
> 2) Click on the parent breadcrumb
> 
> Screenshot 2021-08-02 at 08 46 57
> 3) It leads to empty page. **NOK**
> 
> Screenshot 2021-08-02 at 08 47 22

Well I didn't know we've had this issue so couldn't really fix it :) Thanks, looking into that.

**Comment by siemiatj** [comment]
> Pls fix the case with parent breadcrumb. Thanks

Good catch, a missed import. I wonder why eslint didn't catch it. It used to be pretty good at this.

**Comment by siemiatj** [comment]
Tested on dev instance: https://recordit.co/mV5ypSf9n4

**Review by petrican — APPROVED** [review]
lgtm. Thanks

**Pull request merged**
