### PR TITLE
#3286 adding function, sql process and scheduler  for truncating t_webuiselection

### PR DESCRIPTION
**Pull request by metasnw**
#3286

### CODE REVIEW

**Comment by metas-ts** [comment]
How does it look for a user when he/she e.g. has set some filters and then the two tables are truncated.

@teosarca what's the effort to do it "right"?
I mean, can't we remove the respective selection on `invalidate`? we could do it async, via metas.event..

**Comment by teosarca** [comment]
@metas-ts 

> How does it look for a user when he/she e.g. has set some filters and then the two tables are truncated.

not very cool :)
he might get some weird errors but at the end everything will be empty.


> what's the effort to do it "right"?

( see de.metas.ui.web.view.DefaultView.close(ViewCloseReason))
I would suggest to:
* in DefaultView.close enqueue the view's UUID to some queue/table
* have a background task/scheduler which is checking queued UUIDs and it's removing them from T_WEBUI_ViewSelection and T_WEBUI_ViewSelectionLine.

**Comment by metasnw** [comment]
the job runs once a day at 00:00 and takes 1ms
worse thing that can happen is that the user has to filter again 
this is nothing in comparison to the data growth everybody with lots of data experiences.

I would go with this temp solution and come up with a nicer one laster to replace it.

**Comment by metas-mk** [comment]
@metasnw thanks for the workaround.
@teosarca @metas-ts thanks for your feedback. this temporary solution is fine for me atm until we can tackle the "right" solution.

**Pull request merged**
