### PR TITLE
Fix procurement

### PR DESCRIPTION
**Pull request by mrie04**

### CODE REVIEW

**Comment by metas-ts** [comment]
@Mergifyio copy soft_panda_uat

**Comment by mrie04** [comment]
@Mergifyio copy pipeline/v175 release release_5.175 release_5.176

**Comment by mrie04** [comment]
@Mergifyio copy intensive_care_uat

**Comment by mrie04** [comment]
@Mergifyio copy blue_horizon_uat

**Comment by mrie04** [comment]
@Mergifyio copy vampire_textbook_uat

**Pull request merged**
