### PR TITLE
#3272 provide year and periods for 2018

### PR DESCRIPTION
**Pull request by metasnw**
#3272

### CODE REVIEW

**Comment by metasnw** [comment]
@teosarca I am not sure if I would merge this script as it is.
Currently it does not respect if a period for 2018 is already existing leading to problems if the periods for 2018 already exist.

**Comment by teosarca** [comment]
@metasnw  hmmm, shall i revert it?

**Comment by metasnw** [comment]
@teosarca I would not leave it in master without making it respecting existing data. so, yes. I would revert it.

**Comment by teosarca** [comment]
@metasnw  done, see https://github.com/metasfresh/metasfresh/pull/3277

**Comment by metasnw** [comment]
@teosarca still I need the branch to be able to deploy the script.
is it deleted now?

**Pull request merged**
