### PR TITLE
Gh5970 4

### PR DESCRIPTION
**Pull request by teosarca**
https://github.com/metasfresh/metasfresh/issues/5970

### CODE REVIEW

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.business/src/test/java/de/metas/security/permissions/bpartner_hierarchy/BPartnerHierarchyRecordAccessHandlerTest.java  2
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessGrantRequest.java  2
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessCopyCommand.java  13
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/security/permissions/record_access/UserGroupRecordAccessServiceTest.java  1
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessId.java  3
         

Complexity decreasing per file
==============================
+ de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccess.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metasfresh/metasfresh/pullRequest?prid=5074124&bid=16693164)

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessGrantRequest.java  2
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessCopyCommand.java  13
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessId.java  3
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/security/permissions/record_access/UserGroupRecordAccessServiceTest.java  1
- de.metas.business/src/test/java/de/metas/security/permissions/bpartner_hierarchy/BPartnerHierarchyRecordAccessHandlerTest.java  2
         

Complexity decreasing per file
==============================
+ de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccess.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metasfresh/metasfresh/pullRequest?prid=5074124&bid=16693164)

**Comment by metas-ts** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- de.metas.business/src/test/java/de/metas/security/permissions/bpartner_hierarchy/BPartnerHierarchyRecordAccessHandlerTest.java  2
- de.metas.adempiere.adempiere/base/src/test/java/de/metas/security/permissions/record_access/UserGroupRecordAccessServiceTest.java  1
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessCopyCommand.java  13
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessId.java  3
- de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccessGrantRequest.java  2
         

Complexity decreasing per file
==============================
+ de.metas.adempiere.adempiere/base/src/main/java/de/metas/security/permissions/record_access/RecordAccess.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metasfresh/metasfresh/pullRequest?prid=5074124&bid=16693164)

**Comment by teosarca** [comment]
weird jenkins issue.
moved to https://github.com/metasfresh/metasfresh/pull/6282

**Pull request closed without merging**
