### PR TITLE
Fix CandidateAssignmentServiceTest

### PR DESCRIPTION
**Pull request by metas-ts**

### CODE REVIEW

**Review by teosarca — APPROVED** [review]

**Comment by metas-ts** [comment]
@mergifyio copy pink_rooster_uat

**Comment by metas-ts** [comment]
@mergifyio copy magic_oak_uat

**Comment by metas-ts** [comment]
@Mergifyio copy release_5.175 release

**Comment by teosarca** [comment]
@Mergifyio copy intensive_care_hotfix

**Comment by teosarca** [comment]
@Mergifyio copy mad_orange_uat

**Comment by mrie04** [comment]
@Mergifyio copy modified_carbon_uat

**Comment by metas-ts** [comment]
@mergifyio copy yoyo_uat_update_to_5.175 tasty_ham_uat_update_to_5.175 tenacious_d_uat_update_to_5.175 science_vessel_uat_update_to_5.175

**Comment by metas-ts** [comment]
@mergifyio copy big_coconut_uat secondary_opinion_uat zulu_alpha_uat

**Comment by metas-ts** [comment]
@mergifyio copy clone_wars_uat majestic_kangaroo_uat

**Comment by metas-ts** [comment]
@MergifyIO copy soft_panda_uat

**Pull request merged**
