### PR TITLE
Modular contract log customization and corrections

### PR DESCRIPTION
**Pull request by riadmen**
https://github.com/metasfresh/metasfresh/issues/16294

### CODE REVIEW

**Review by mrie04 — CHANGES_REQUESTED** [review]
pls move the file to `de.metas.contracts` and add 2 empty lines at the end

**Comment by riadmen** [comment]
> de.metas.contracts
correction done

**Review by mrie04 — COMMENTED** [review]
lgtm

**Review by mrie04 — APPROVED** [review]
lgtm, failling cucumbers are introduced by another issue

**Pull request merged**
