### PR TITLE
Re-introduce AD_*_Access_IDs; make sure role_access_update() db function is not wasting sequence numbers

### PR DESCRIPTION
**Pull request by teosarca**
- **improve role_access_update db functions by incrementally updating current data in order to minimize the sequence consumption**
- **TablePrimaryKeyGenerator: check migrationLogger.isLogTableName when considering project ID server to be used**
- **role_access_update: make sure we perform only the minimal changes in order to not waste the IDs**
- **Add back single primary key columns from AD_*_Access tables**

### CODE REVIEW

**Review by mrie04 — APPROVED** [review]
lgtm

**Comment by teosarca** [comment]
@Mergifyio copy release

**Comment by teosarca** [comment]
https://github.com/Mergifyio copy release_5.175

**Comment by teosarca** [comment]
https://github.com/Mergifyio copy modified_carbon_uat

**Pull request merged**
