### PR TITLE
Fix js builds (mobileUI and procurementUI)

### PR DESCRIPTION
**Pull request by metas-ts**
thx @cp-ps

### CODE REVIEW

**Comment by mrie04** [comment]
@Mergifyio copy pipeline/v175 release release_5.175 release_5.176

**Comment by mrie04** [comment]
@Mergifyio copy secondary_opinion_uat

**Comment by metas-ts** [comment]
@mergifyio copy soft_panda_uat

**Comment by mrie04** [comment]
@Mergifyio copy inner_silence_uat

**Comment by metas-ts** [comment]
@Mergifyio copy intensive_care_uat

**Comment by mrie04** [comment]
@Mergifyio copy blue_horizon_uat

**Comment by metas-ts** [comment]
https://github.com/Mergifyio copy intensive_care_hotfix

**Comment by metas-ts** [comment]
@MergifyIO copy tasty_ham_uat tasty_ham_hotfix

**Pull request merged**
