### PR TITLE
Fixes for MyKloudz GitHub issue Nos. 18, 16 & 32

### PR DESCRIPTION
**Pull request by mykloudz**
#5358

### CODE REVIEW

**Comment by mykloudz** [comment]
This PR contains the supporting methods for the fix in PR (https://github.com/metasfresh/metasfresh-webui-api/pull/1222), which are GitHub issue No 18 & 16.

Also it contains the fix for "By-Products not being shown in the HU-bin when we open it for issuing them as components during Manufacturing Order Processing" which is GitHub issue No 32.

**Comment by roopesh-kh** [comment]
Hi @metasnw, @metas-ts , Can you please merge this PR.

**Comment by metas-ts** [comment]
hi @roopesh-kh (cc @metasnw ) 

we figured out that our build-system can't set the two PRs (this one and https://github.com/metasfresh/metasfresh-webui-api/pull/1222 ) into relation and therefore the build fails.

I created the team https://github.com/orgs/metasfresh/teams/as121 with write-access to both metasfresh and metasfresh-api and invited you and @mykloudz to it.

I'm painfully aware that this is annoying, but could you pls check out the two repos, create a branch in each and apply your changes in there?
About the branch name: 
* it need to be the same in both repos.
* by our best practice it would be `gh5358-app`; named after the issue https://github.com/metasfresh/metasfresh/issues/5358
* also, when committing, please paste a reference to (e.g. the URL of) issue https://github.com/metasfresh/metasfresh/issues/5358 into each commit message.

Sorry for the inconvenience, but this is the first cross-repo contribution from a 3rd party and we weren't fully aware of the implications.

Best regards
Tobi

**Comment by mykloudz** [comment]
> hi @roopesh-kh (cc @metasnw )
> 
> we figured out that our build-system can't set the two PRs (this one and [metasfresh/metasfresh-webui-api#1222](https://github.com/metasfresh/metasfresh-webui-api/pull/1222) ) into relation and therefore the build fails.
> 
> I created the team https://github.com/orgs/metasfresh/teams/as121 with write-access to both metasfresh and metasfresh-api and invited you and @mykloudz to it.
> 
> I'm painfully aware that this is annoying, but could you pls check out the two repos, create a branch in each and apply your changes in there?
> About the branch name:
> 
> * it needs to be the same in both repos.
> * by our best practice it would be `gh5358-app`; named after the issue #5358
> * also, when committing, please paste a reference to (e.g. the URL of) issue #5358 into each commit message.
> 
> Sorry for the inconvenience, but this is the first cross-repo contribution from a 3rd party and we weren't fully aware of the implications.
> 
> Best regards
> 

> hi @roopesh-kh (cc @metasnw )
> 
> we figured out that our build-system can't set the two PRs (this one and [metasfresh/metasfresh-webui-api#1222](https://github.com/metasfresh/metasfresh-webui-api/pull/1222) ) into relation and therefore the build fails.
> 
> I created the team https://github.com/orgs/metasfresh/teams/as121 with write-access to both metasfresh and metasfresh-api and invited you and @mykloudz to it.
> 
> I'm painfully aware that this is annoying, but could you pls check out the two repos, create a branch in each and apply your changes in there?
> About the branch name:
> 
> * it needs to be the same in both repos.
> * by our best practice it would be `gh5358-app`; named after the issue #5358
> * also, when committing, please paste a reference to (e.g. the URL of) issue #5358 into each commit message.
> 
> Sorry for the inconvenience, but this is the first cross-repo contribution from a 3rd party and we weren't fully aware of the implications.
> 
> Best regards
> Tobi

@metas-ts, commited our changes with new branch named: 'gh5358-app' into both metasfresh/metasfresh and metasfresh/metasfresh-api repos. 

These are the Commit URLs for your reference: https://github.com/metasfresh/metasfresh/commit/e6a95a2d11d3ac03e3e87de25cac5892c01bd0ce
https://github.com/metasfresh/metasfresh-webui-api/commit/a27f53ff1484bd017094ec234e9b6df80b41cd36

And do we need to raise any PRs again?

**Comment by metas-ts** [comment]
hi @mykloudz (cc @metasnw )

> @metas-ts, commited our changes with new branch named: 'gh5358-app' into both metasfresh/metasfresh and metasfresh/metasfresh-api repos.

thx. FYI your build https://jenkins.metasfresh.com/job/metasfresh/job/gh5358-app/1/ succeeded, but was unstable, because yesterday's `master` was unstable at a certain time. 
I just merged the latest master into your branches, that should fix it.

> And do we need to raise any PRs again?

yes, pls close these "fork" PRs and created two new "branch" PRs.

@metasnw as soon as https://jenkins.metasfresh.com/job/metasfresh/job/gh5358-app/2/ is green we should be able to provied the guys with a dev-instance for further QA.

**Pull request closed without merging**
