### PR TITLE
prevent NPE when getting email address for inout

### PR DESCRIPTION
**Pull request by metas-ts**

### CODE REVIEW

**Comment by teosarca** [comment]
@metas-ts  shall we add `patch_mgmt` label to this?

**Comment by metas-ts** [comment]
@teosarca yes. done

**Comment by metas-ts** [comment]
going to try distributing this fix with mergify

**Comment by metas-ts** [comment]
@Mergifyio copy adorable_badger_uat big_coconut_uat inner_silence_uat intensive_care_uat mad_orange_uat master neon_underwear_uat release tasty_ham_uat tenacious_d_uat week_end_uat yoyo_uat

**Comment by metas-ts** [comment]
this bug was fixed aprox one week after introduction. each branch that had the bug now also has the fix

**Pull request merged**
